config/routes.rb
Rails.application.routes.draw do

  resources :ping_url_results

  resources :ping_urls do
    get :check, on: :member
  end

  root 'ping_urls#index'

end

app/models/ping_url.rb
class PingUrl < ActiveRecord::Base

  has_many :ping_url_results

end

app/models/ping_url_result.rb
class PingUrlResult < ActiveRecord::Base

  belongs_to :ping_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/basic_auth_concern.rb
module BasicAuthConcern
  extend ActiveSupport::Concern

  included do
    before_action :basic_auth_action
  end

  def basic_auth_action
    return true if ENV['ENABLE_BASIC_AUTH'].to_i != 1

    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_ID'] &&
      password == ENV['BASIC_AUTH_PASS']
    end
  end

end

app/controllers/ping_url_results_controller.rb
class PingUrlResultsController < ApplicationController
  before_action :set_ping_url_result, only: [:show, :edit, :update, :destroy]

  # GET /ping_url_results
  # GET /ping_url_results.json
  def index
    @ping_url_results = PingUrlResult.all
  end

  # GET /ping_url_results/1
  # GET /ping_url_results/1.json
  def show
  end

  # GET /ping_url_results/new
  def new
    @ping_url_result = PingUrlResult.new
  end

  # GET /ping_url_results/1/edit
  def edit
  end

  # POST /ping_url_results
  # POST /ping_url_results.json
  def create
    @ping_url_result = PingUrlResult.new(ping_url_result_params)

    respond_to do |format|
      if @ping_url_result.save
        format.html { redirect_to @ping_url_result, notice: 'Ping url result was successfully created.' }
        format.json { render :show, status: :created, location: @ping_url_result }
      else
        format.html { render :new }
        format.json { render json: @ping_url_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ping_url_results/1
  # PATCH/PUT /ping_url_results/1.json
  def update
    respond_to do |format|
      if @ping_url_result.update(ping_url_result_params)
        format.html { redirect_to @ping_url_result, notice: 'Ping url result was successfully updated.' }
        format.json { render :show, status: :ok, location: @ping_url_result }
      else
        format.html { render :edit }
        format.json { render json: @ping_url_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ping_url_results/1
  # DELETE /ping_url_results/1.json
  def destroy
    @ping_url_result.destroy
    respond_to do |format|
      format.html { redirect_to ping_url_results_url, notice: 'Ping url result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ping_url_result
      @ping_url_result = PingUrlResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ping_url_result_params
      params.require(:ping_url_result).permit(:ping_url_id, :response_body)
    end
end

app/controllers/ping_urls_controller.rb
class PingUrlsController < ApplicationController

  before_action :set_ping_url, only: [:show, :edit, :update, :destroy, :check]

  # GET /ping_urls
  # GET /ping_urls.json
  def index
    @ping_urls = PingUrl.all
  end

  # GET /ping_urls/1
  # GET /ping_urls/1.json
  def show
  end

  # GET /ping_urls/new
  def new
    @ping_url = PingUrl.new
  end

  # GET /ping_urls/1/edit
  def edit
  end

  # POST /ping_urls
  # POST /ping_urls.json
  def create
    @ping_url = PingUrl.new(ping_url_params)

    respond_to do |format|
      if @ping_url.save
        format.html { redirect_to @ping_url, notice: 'Ping url was successfully created.' }
        format.json { render :show, status: :created, location: @ping_url }
      else
        format.html { render :new }
        format.json { render json: @ping_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ping_urls/1
  # PATCH/PUT /ping_urls/1.json
  def update
    respond_to do |format|
      if @ping_url.update(ping_url_params)
        format.html { redirect_to @ping_url, notice: 'Ping url was successfully updated.' }
        format.json { render :show, status: :ok, location: @ping_url }
      else
        format.html { render :edit }
        format.json { render json: @ping_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ping_urls/1
  # DELETE /ping_urls/1.json
  def destroy
    @ping_url.destroy
    respond_to do |format|
      format.html { redirect_to ping_urls_url, notice: 'Ping url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check
    PingService.ping(@ping_url, true)
    redirect_to action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ping_url
      @ping_url = PingUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ping_url_params
      params.require(:ping_url).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ping_url_results_helper.rb
module PingUrlResultsHelper
end

app/helpers/ping_urls_helper.rb
module PingUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PingUrls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ping_url_results/_form.html.slim
= form_for @ping_url_result do |f|
  - if @ping_url_result.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ping_url_result.errors.count, "error")} prohibited this ping_url_result from being saved:"
      ul
        - @ping_url_result.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :ping_url
    = f.text_field :ping_url
  .field
    = f.label :response_body
    = f.text_area :response_body
  .actions = f.submit

app/views/ping_url_results/edit.html.slim
h1 Editing ping_url_result

== render 'form'

= link_to 'Show', @ping_url_result
'|
= link_to 'Back', ping_url_results_path

app/views/ping_url_results/index.html.slim
h1 Listing ping_url_results

table
  thead
    tr
      th Ping url
      th Response body
      th
      th
      th

  tbody
    - @ping_url_results.each do |ping_url_result|
      tr
        td = ping_url_result.ping_url
        td = ping_url_result.response_body
        td = link_to 'Show', ping_url_result
        td = link_to 'Edit', edit_ping_url_result_path(ping_url_result)
        td = link_to 'Destroy', ping_url_result, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Ping url result', new_ping_url_result_path

app/views/ping_url_results/new.html.slim
h1 New ping_url_result

== render 'form'

= link_to 'Back', ping_url_results_path

app/views/ping_url_results/show.html.slim
p#notice = notice

p
  strong Ping url:
  = link_to @ping_url_result.ping_url.url, @ping_url_result.ping_url
p
  strong Response body:
  pre = @ping_url_result.response_body

= link_to 'Edit', edit_ping_url_result_path(@ping_url_result)
'|
= link_to 'Back', ping_url_results_path

app/views/ping_urls/_form.html.slim
= form_for @ping_url do |f|
  - if @ping_url.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ping_url.errors.count, "error")} prohibited this ping_url from being saved:"
      ul
        - @ping_url.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_area :url
  .actions = f.submit

app/views/ping_urls/edit.html.slim
h1 Editing ping_url

== render 'form'

= link_to 'Show', @ping_url
'|
= link_to 'Back', ping_urls_path

app/views/ping_urls/index.html.slim
h1 Listing ping_urls

table
  thead
    tr
      th Url
      th
      th

  tbody
    - @ping_urls.each do |ping_url|
      tr
        td = link_to ping_url.url, ping_url
        td = link_to 'Edit', edit_ping_url_path(ping_url)
        td = link_to 'Destroy', ping_url, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Ping url', new_ping_url_path

app/views/ping_urls/new.html.slim
h1 New ping_url

== render 'form'

= link_to 'Back', ping_urls_path

app/views/ping_urls/show.html.slim
p#notice = notice

p
  strong Url:
  = @ping_url.url

div
  - @ping_url.ping_url_results.each do |ping_url_result|
    div
      div = link_to truncate(ping_url_result.response_body), ping_url_result
      div = l ping_url_result.created_at

div
  = link_to 'Check', check_ping_url_path(@ping_url)

= link_to 'Edit', edit_ping_url_path(@ping_url)
'|
= link_to 'Back', ping_urls_path